<a href="https://colab.research.google.com/github/jadhavsiya481-hash/Python-Basic-Projects/blob/main/Session_13_AIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Q1

import numpy as np

arr = np.array([10,20,30,40,50])
print("1D Array:")
print(arr)
print("Shape:",arr.shape)
print("DataType:",arr.dtype)

arr2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
print("2D Array:")
print(arr2)
print("Shape:",arr2.shape)
print("DataType:",arr2.dtype)



1D Array:
[10 20 30 40 50]
Shape: (5,)
DataType: int64
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
DataType: int64


In [6]:
#Q2
import numpy as np

a = np.zeros(8)
b = np.ones((4,4))
c = np.zeros((3,3))

print("1D Array")
print(a)
print("4x4 Matrix")
print(b)
print("3x3 Matrix")
print(c)

1D Array
[0. 0. 0. 0. 0. 0. 0. 0.]
4x4 Matrix
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3x3 Matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#Q3
import numpy as np

a = np.arange(0,21,1)
b = np.arange(10,51,2)
c = np.arange(5,101,5)

print("0 to 20:")
print(a)
print("10 10 50:")
print(b)
print("5 to 100")
print(c)




0 to 20:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
10 10 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
5 to 100
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [10]:
#Q4
import numpy as np

a = np.linspace(0,5,10)
b = np.linspace(-10,10,15)

print("0 to 5:")
print(a)
print("Length:",len(a))

print("-10 to 10:")
print(b)
print("Length:",len(b))

0 to 5:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10
-10 to 10:
[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length: 15


In [15]:
#Q5
import numpy as np

a = np.random.rand(10)
b = np.random.randint(10,51,(4,5))
c = np.random.randn(3,3)

print("1D Array")
print(a)
print("3x3 Matrix")
print(b)
print("Random integer array")
print(c)


1D Array
[0.20994953 0.3496126  0.22535657 0.63186946 0.94840414 0.14719765
 0.4989913  0.58893138 0.63423319 0.57912927]
3x3 Matrix
[[28 18 14 28 13]
 [49 45 47 13 43]
 [36 30 41 36 30]
 [13 20 20 17 36]]
Random integer array
[[-0.80448107 -0.89461037 -1.71258218]
 [ 0.7757143   0.03240474 -0.05633768]
 [ 0.00244953 -0.46398261 -0.03084966]]


In [16]:
#Q6
import numpy as np

v1 = np.array([2,4,6,8])
v2 = np.array([1,3,5,7])

print("Addition:")
print(v1+v2)
print("Subtraction:")
print(v1-v2)
print("Element-wise Multiplication:")
print(v1*v2)
print("Dot Product:")
print(np.dot(v1,v2))


Addition:
[ 3  7 11 15]
Subtraction:
[1 1 1 1]
Element-wise Multiplication:
[ 2 12 30 56]
Dot Product:
100


In [18]:
#Q7
import numpy as np

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b = np.array([
    [10,11,12],
    [13,14,15],
    [16,17,18]
])

print("Matrix A:")
print(a)
print("Matrix B:")
print(b)
print("Matrix Addition:")
print(a + b)
print("Matrix Multiplication:")
print(a @ b)
print("Element-wise Multiplication:")
print(a * b)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Matrix Addition:
[[11 13 15]
 [17 19 21]
 [23 25 27]]
Matrix Multiplication:
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
Element-wise Multiplication:
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [20]:
#Q8
import numpy as np

arr = np.random.randint(1,101,(4,4))
print("Array:")
print(arr)

print("Shape:",arr.shape)
print("Size:",arr.size)
print("DataType:",arr.dtype)
print("Dimension:",arr.ndim)
print("Minimum Value:",arr.min())
print("Maximum Value:",arr.max())


Array:
[[ 51   2  46  74]
 [ 93  68  62  85]
 [ 27  18  55 100]
 [ 14  44  94  54]]
Shape: (4, 4)
Size: 16
DataType: int64
Dimension: 2
Minimum Value: 2
Maximum Value: 100


In [21]:
#Q9
import numpy as np

arr = np.random.randint(1,52,20)
matrix = arr.reshape(4,5)
print("Matrix:")
print(matrix)

print("Sum:",matrix.sum())
print("Mean:",matrix.mean())
print("Standard Deviation:",matrix.std())
print("Max value in each row:")
print(matrix.max(axis=1))

Matrix:
[[12 51  6  3 47]
 [36  5 16 26 38]
 [38 28 26  8 12]
 [38 18 40 12 51]]
Sum: 511
Mean: 25.55
Standard Deviation: 15.59639381395584
Max value in each row:
[51 38 38 51]


In [26]:
#Q10
import numpy as np

n = int(input("How many numbers do you wanna generate?"))
arr = np.random.randint(10,101,n)

print("array")
print(arr)

print("Mean:",arr.mean())
print("Median:",np.median(arr))
print("Standard Deviation:",arr.std())
print("Minimum:",arr.min())
print("Maximum:",arr.max())

if n%2 == 0:
  matrix = arr.reshape(2,n//2)
  print("array")
  print(matrix)

  print("Row-wise Sum:")
  print(matrix.sum(axis=1))

else:
  print("Cannot reshape into 2D array.")


How many numbers do you wanna generate?20
array
[69 33 47 43 32 62 62 65 27 19 41 91 22 56 30 61 90 74 11 52]
Mean: 49.35
Median: 49.5
Standard Deviation: 22.17041948182307
Minimum: 11
Maximum: 91
array
[[69 33 47 43 32 62 62 65 27 19]
 [41 91 22 56 30 61 90 74 11 52]]
Row-wise Sum:
[459 528]
