<a href="https://colab.research.google.com/github/jadhavsiya481-hash/Python-Basic-Projects/blob/main/Session_14_AIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Q1
import numpy as np
arr = np.random.randint(10,101,size=(5,6))
print(arr)
print
print("Shape of array:",arr.shape)
print("Size of array:",arr.size)
print("Data type of array:",arr.dtype)

[[ 66  83  13  82  97  99]
 [ 37  30  28  79 100  87]
 [ 59  27  97  10  53  54]
 [ 39  60  31  30  65  17]
 [ 28  40  12  62  47  45]]
Shape of array: (5, 6)
Size of array: 30
Data type of array: int64


In [3]:
#Q2
import numpy as np

arr = np.random.randint(1,51,size=20)
print("Array:")
print(arr)
print("Sum of all elements:",arr.sum())
print("Mean:",arr.mean())
print("Maximum value:",arr.max())
print("Minimum value:",arr.min())
print("Index of maximum value:",arr.argmax())
print("Index of minimum value:",arr.argmin())
print("Standard Deviation:",arr.std())

Array:
[50 15 24 42  1  9 40  4 46 17  5  2 44 40 47 43 47 11  2 11]
Sum of all elements: 500
Mean: 25.0
Maximum value: 50
Minimum value: 1
Index of maximum value: 0
Index of minimum value: 4
Standard Deviation: 18.365728953678914


In [4]:
#Q3
import numpy as np

arr = np.random.randint(20,81,(4,5))

print(arr)
print("Minimum:",arr.min())
print("Maximum:",arr.max())
print("Mean:",arr.mean())
print("Sum:",arr.sum())
print("Standard Deviation:",arr.std())
print("Row Sum:",arr.sum(axis=1))
print("Column Sum:",arr.sum(axis=0))


[[20 67 41 25 43]
 [76 72 77 33 56]
 [48 70 59 26 54]
 [28 27 56 59 37]]
Minimum: 20
Maximum: 77
Mean: 48.7
Sum: 974
Standard Deviation: 18.02803372528463
Row Sum: [196 314 257 207]
Column Sum: [172 236 233 143 190]


In [7]:
#Q4
import numpy as np

arr = np.arange(1,25)

a = arr.reshape(4,6)
print("Shape:",a.shape)

b = arr.reshape(3,8)
print("Shape:",b.shape)

c = arr.reshape(2,3,4)
print("Shape:",c.shape)

Shape: (4, 6)
Shape: (3, 8)
Shape: (2, 3, 4)


In [8]:
#Q5

import numpy as np

arr = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120],
])
print(arr)
print("First Row:",arr[0])
print("Last Column:",arr[:,-1])
print("Center 2x2:",arr[0:2,1:3])
print("Even Numbers:",arr[arr%2==0])

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
First Row: [10 20 30 40]
Last Column: [ 40  80 120]
Center 2x2: [[20 30]
 [60 70]]
Even Numbers: [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [9]:
#Q6

import numpy as np

arr = np.random.randint(1,101,size=(5,5))
print(arr)
print("Diagonal:",np.diag(arr))
print("Larger than 50:",arr[arr>50])

arr[arr<30]=0

print("Modified Array:")
print(arr)


[[29 36 83 68 61]
 [76 77 96 49 32]
 [57  1 68 94 73]
 [53 83 41 65 43]
 [ 9 25 50 77 51]]
Diagonal: [29 77 68 65 51]
Larger than 50: [83 68 61 76 77 96 57 68 94 73 53 83 65 77 51]
Modified Array:
[[ 0 36 83 68 61]
 [76 77 96 49 32]
 [57  0 68 94 73]
 [53 83 41 65 43]
 [ 0  0 50 77 51]]


In [11]:
#Q7

import numpy as np

a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Power:",a**b)
print("Modulo:",a%b)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Power: [       10       400     27000   2560000 312500000]
Modulo: [0 0 0 0 0]


In [12]:
#Q8

import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print("Element-wise Multiplication:", A*B)
print("Matrix Multiplication:", A@B)

Element-wise Multiplication: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Multiplication: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [13]:
#Q9

import numpy as np

arr = np.random.randn(6,6)

print(arr)
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Datatype:",arr.dtype)
print("Max Index:",arr.argmax())
print("Min Index:",arr.argmin())
print("Top Left 3x3:",arr[:3,:3])

arr[arr<0] = abs(arr[arr<0])

print("Mean:",arr.mean())

[[ 2.18120354 -0.04379168 -0.21184584 -1.30645674 -0.31278604  0.0119272 ]
 [ 0.09398707  1.18788055 -0.27785731 -1.37263658  0.52246108 -0.42801734]
 [ 0.96401175 -1.65745681 -0.71853817 -0.44960656 -0.40131057 -0.57582468]
 [ 0.8181473   0.58475985 -0.92314287 -0.02283334 -0.26188418  1.6613614 ]
 [ 0.09237029 -0.30815816  1.27899058  0.37679706  2.07591472 -1.65299039]
 [-0.72990355  0.92559886 -0.24286145  0.19695206 -1.39007801 -1.16049816]]
Shape: (6, 6)
Size: 36
Datatype: float64
Max Index: 0
Min Index: 13
Top Left 3x3: [[ 2.18120354 -0.04379168 -0.21184584]
 [ 0.09398707  1.18788055 -0.27785731]
 [ 0.96401175 -1.65745681 -0.71853817]]
Mean: 0.7616900486660904


In [18]:
#Q10

import numpy as np

marks = np.random.randint(30,101,(10,5))
print("Student Marks:")
print(marks)

total_marks = np.sum(marks, axis=1)
avg = np.mean(marks, axis=1)

print("Student Result:")
for i in range(10):
    print(f"Student {i+1}: Total Marks = {total_marks[i]}, Average Marks = {avg[i]:.2f}")

highest = np.argmax(total_marks)
lowest = np.argmin(total_marks)

print(f"Highest Total Marks: Student {highest+1} ({total_marks[highest]})")
print(f"Lowest Total Marks: Student {lowest+1} ({total_marks[lowest]})")
print(f"Class Mean: {np.mean(total_marks):.2f}")
print(f"Class Standard Deviation: {np.std(total_marks):.2f}")
print(f"Marks of top 3 students:")

top3 = np.argsort(total_marks)[-3:]
print(marks[top3])

Student Marks:
[[ 50  80  97  39 100]
 [ 89  95  55  99  68]
 [ 73  57  66  79  76]
 [ 96  84  75  66  51]
 [ 72  99  45  95  72]
 [ 63  56  57  50  51]
 [ 49  85  96  73  55]
 [ 61  94  31  56  69]
 [ 47  56  73  48  37]
 [ 66  44  55  88  67]]
Student Result:
Student 1: Total Marks = 366, Average Marks = 73.20
Student 2: Total Marks = 406, Average Marks = 81.20
Student 3: Total Marks = 351, Average Marks = 70.20
Student 4: Total Marks = 372, Average Marks = 74.40
Student 5: Total Marks = 383, Average Marks = 76.60
Student 6: Total Marks = 277, Average Marks = 55.40
Student 7: Total Marks = 358, Average Marks = 71.60
Student 8: Total Marks = 311, Average Marks = 62.20
Student 9: Total Marks = 261, Average Marks = 52.20
Student 10: Total Marks = 320, Average Marks = 64.00
Highest Total Marks: Student 2 (406)
Lowest Total Marks: Student 9 (261)
Class Mean: 340.50
Class Standard Deviation: 44.50
Marks of top 3 students:
[[96 84 75 66 51]
 [72 99 45 95 72]
 [89 95 55 99 68]]
